"""Add pfref_id to player table

Revision ID: 03823198a0c1
Revises: 9c7ef399630d
Create Date: 2025-01-26 22:39:37.478887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03823198a0c1'
down_revision: Union[str, None] = '9c7ef399630d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_week', sa.Column('tm_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'player_week', 'teams', ['tm_id'], ['team_id'])
    op.add_column('players', sa.Column('pfref_id', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'pfref_id')
    op.drop_constraint(None, 'player_week', type_='foreignkey')
    op.drop_column('player_week', 'tm_id')
    # ### end Alembic commands ###
