"""Add fantasy-platform tables

Revision ID: 29df909e2352
Revises: 915fa6c34575
Create Date: 2025-02-01 00:29:44.396130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '29df909e2352'
down_revision: Union[str, None] = '915fa6c34575'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform',
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('platform_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('platform_id')
    )
    op.create_table('league_season',
    sa.Column('league_season_id', sa.Integer(), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=True),
    sa.Column('platform_league_id', sa.String(length=50), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('scoring_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['platform_id'], ['platform.platform_id'], ),
    sa.PrimaryKeyConstraint('league_season_id'),
    sa.UniqueConstraint('platform_id', 'platform_league_id', 'season')
    )
    op.create_table('league_team',
    sa.Column('league_team_id', sa.Integer(), nullable=False),
    sa.Column('league_season_id', sa.Integer(), nullable=True),
    sa.Column('platform_team_id', sa.String(length=50), nullable=False),
    sa.Column('team_name', sa.String(length=50), nullable=True),
    sa.Column('team_abbreviation', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['league_season_id'], ['league_season.league_season_id'], ),
    sa.PrimaryKeyConstraint('league_team_id'),
    sa.UniqueConstraint('league_season_id', 'platform_team_id')
    )
    op.create_table('draft_team',
    sa.Column('league_team_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('draft_pick_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['league_team_id'], ['league_team.league_team_id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.PrimaryKeyConstraint('league_team_id', 'player_id')
    )
    op.create_table('weekly_starter',
    sa.Column('league_team_id', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('start', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['league_team_id'], ['league_team.league_team_id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.PrimaryKeyConstraint('league_team_id', 'week', 'player_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weekly_starter')
    op.drop_table('draft_team')
    op.drop_table('league_team')
    op.drop_table('league_season')
    op.drop_table('platform')
    # ### end Alembic commands ###
