"""Add fields for player week statistics

Revision ID: 2a956fc2909d
Revises: 8908adf37ee2
Create Date: 2025-01-26 21:43:39.509199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a956fc2909d'
down_revision: Union[str, None] = '8908adf37ee2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_team')
    op.add_column('player_week', sa.Column('pass_cmp', sa.Integer(), nullable=True))
    op.add_column('player_week', sa.Column('pass_att', sa.Integer(), nullable=True))
    op.add_column('player_week', sa.Column('pass_yds', sa.Integer(), nullable=True))
    op.add_column('player_week', sa.Column('pass_td', sa.Integer(), nullable=True))
    op.add_column('player_week', sa.Column('pass_int', sa.Integer(), nullable=True))
    op.add_column('player_week', sa.Column('sacks', sa.Integer(), nullable=True))
    op.add_column('player_week', sa.Column('sack_yds', sa.Integer(), nullable=True))
    op.add_column('player_week', sa.Column('rush_att', sa.Integer(), nullable=True))
    op.add_column('player_week', sa.Column('rush_yds', sa.Integer(), nullable=True))
    op.add_column('player_week', sa.Column('rush_td', sa.Integer(), nullable=True))
    op.add_column('player_week', sa.Column('targets', sa.Integer(), nullable=True))
    op.add_column('player_week', sa.Column('receptions', sa.Integer(), nullable=True))
    op.add_column('player_week', sa.Column('rec_yds', sa.Integer(), nullable=True))
    op.add_column('player_week', sa.Column('rec_td', sa.Integer(), nullable=True))
    op.add_column('player_week', sa.Column('fumbles', sa.Integer(), nullable=True))
    op.add_column('player_week', sa.Column('xpm', sa.Integer(), nullable=True))
    op.add_column('player_week', sa.Column('xpa', sa.Integer(), nullable=True))
    op.add_column('player_week', sa.Column('fgm', sa.Integer(), nullable=True))
    op.add_column('player_week', sa.Column('fga', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player_week', 'fga')
    op.drop_column('player_week', 'fgm')
    op.drop_column('player_week', 'xpa')
    op.drop_column('player_week', 'xpm')
    op.drop_column('player_week', 'fumbles')
    op.drop_column('player_week', 'rec_td')
    op.drop_column('player_week', 'rec_yds')
    op.drop_column('player_week', 'receptions')
    op.drop_column('player_week', 'targets')
    op.drop_column('player_week', 'rush_td')
    op.drop_column('player_week', 'rush_yds')
    op.drop_column('player_week', 'rush_att')
    op.drop_column('player_week', 'sack_yds')
    op.drop_column('player_week', 'sacks')
    op.drop_column('player_week', 'pass_int')
    op.drop_column('player_week', 'pass_td')
    op.drop_column('player_week', 'pass_yds')
    op.drop_column('player_week', 'pass_att')
    op.drop_column('player_week', 'pass_cmp')
    op.create_table('player_team',
    sa.Column('player_team_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('season', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('week', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tm_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], name='player_team_player_id_fkey'),
    sa.PrimaryKeyConstraint('player_team_id', name='player_team_pkey'),
    sa.UniqueConstraint('player_id', 'season', 'week', name='player_team_player_id_season_week_key')
    )
    # ### end Alembic commands ###
