"""Index on playerplatform ids and create relatinship

Revision ID: 37ff950f46ad
Revises: fa75498f5d80
Create Date: 2025-02-06 23:39:29.271678

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "37ff950f46ad"
down_revision: Union[str, None] = "fa75498f5d80"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_player_espn_id"), "player", ["espn_id"], unique=False)
    op.create_index(op.f("ix_player_pfref_id"), "player", ["pfref_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_player_pfref_id"), table_name="player")
    op.drop_index(op.f("ix_player_espn_id"), table_name="player")
    # ### end Alembic commands ###
