"""Update columns in tables

Revision ID: 61c16241e9ed
Revises: f9462cab83bf
Create Date: 2025-02-23 00:48:41.641457

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "61c16241e9ed"
down_revision: Union[str, None] = "f9462cab83bf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "league_weekly_team", sa.Column("player_season_id", sa.Integer(), nullable=True)
    )
    op.drop_constraint(
        "league_weekly_team_player_week_id_fkey",
        "league_weekly_team",
        type_="foreignkey",
    )
    op.drop_constraint(
        "weekly_starter_player_id_fkey", "league_weekly_team", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "league_weekly_team",
        "player_season",
        ["player_season_id"],
        ["player_season_id"],
    )
    op.drop_column("league_weekly_team", "player_week_id")
    op.drop_column("league_weekly_team", "player_id")
    op.create_unique_constraint(None, "player_week", ["player_season_id", "week"])
    op.drop_constraint(
        "player_week_espn_player_week_id_fkey", "player_week_espn", type_="foreignkey"
    )
    op.drop_column("player_week_espn", "player_week_id")
    op.drop_column("player_week_espn", "player_week_espn_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "player_week_espn",
        sa.Column(
            "player_week_espn_id", sa.INTEGER(), autoincrement=True, nullable=False
        ),
    )
    op.add_column(
        "player_week_espn",
        sa.Column("player_week_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "player_week_espn_player_week_id_fkey",
        "player_week_espn",
        "player_week_reference_deprecated",
        ["player_week_id"],
        ["player_week_id"],
    )
    op.drop_constraint(None, "player_week", type_="unique")
    op.add_column(
        "league_weekly_team",
        sa.Column("player_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "league_weekly_team",
        sa.Column("player_week_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "league_weekly_team", type_="foreignkey")
    op.create_foreign_key(
        "weekly_starter_player_id_fkey",
        "league_weekly_team",
        "player",
        ["player_id"],
        ["player_id"],
    )
    op.create_foreign_key(
        "league_weekly_team_player_week_id_fkey",
        "league_weekly_team",
        "player_week_reference_deprecated",
        ["player_week_id"],
        ["player_week_id"],
    )
    op.drop_column("league_weekly_team", "player_season_id")

    # ### end Alembic commands ###
