"""updated migration

Revision ID: 639c1bee4462
Revises: 
Create Date: 2025-01-23 20:50:56.225528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '639c1bee4462'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.create_table('teams',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('team_id')
    )
    op.create_table('games',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('tm_id', sa.Integer(), nullable=True),
    sa.Column('opp_id', sa.Integer(), nullable=True),
    sa.Column('home_away', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['opp_id'], ['teams.team_id'], ),
    sa.ForeignKeyConstraint(['tm_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('game_id'),
    sa.UniqueConstraint('season', 'week', 'tm_id')
    )
    op.create_table('player_season',
    sa.Column('player_season_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('position', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.PrimaryKeyConstraint('player_season_id'),
    sa.UniqueConstraint('player_id', 'season')
    )
    op.create_table('player_team',
    sa.Column('player_team_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('tm_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.PrimaryKeyConstraint('player_team_id'),
    sa.UniqueConstraint('player_id', 'season', 'week')
    )
    op.create_table('player_week',
    sa.Column('player_week_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.PrimaryKeyConstraint('player_week_id')
    )
    op.create_table('team_names',
    sa.Column('team_name_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('tm_id', sa.Integer(), nullable=True),
    sa.Column('team_name', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['tm_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('team_name_id'),
    sa.UniqueConstraint('season', 'tm_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_names')
    op.drop_table('player_week')
    op.drop_table('player_team')
    op.drop_table('player_season')
    op.drop_table('games')
    op.drop_table('teams')
    op.drop_table('players')
    # ### end Alembic commands ###
