"""Change column in WeeklyStarter table

Revision ID: 81c2bd0725f5
Revises: 37ff950f46ad
Create Date: 2025-02-08 15:52:17.446210

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "81c2bd0725f5"
down_revision: Union[str, None] = "37ff950f46ad"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "weekly_starter",
        sa.Column("lineup_position", sa.String(length=50), nullable=False),
    )
    op.drop_column("weekly_starter", "start")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "weekly_starter",
        sa.Column("start", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.drop_column("weekly_starter", "lineup_position")
    # ### end Alembic commands ###
