"""Add game_date to games table

Revision ID: 8908adf37ee2
Revises: ef7cc5d54adb
Create Date: 2025-01-25 14:54:25.783942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8908adf37ee2'
down_revision: Union[str, None] = 'ef7cc5d54adb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('game_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'game_date')
    # ### end Alembic commands ###
