"""Add appropriate uniqueness constraints

Revision ID: 915fa6c34575
Revises: 03823198a0c1
Create Date: 2025-01-26 23:57:28.726979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '915fa6c34575'
down_revision: Union[str, None] = '03823198a0c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('player_week', 'points',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.create_unique_constraint(None, 'player_week', ['player_id', 'season', 'week'])
    op.create_unique_constraint(None, 'teams', ['team_pfref_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teams', type_='unique')
    op.drop_constraint(None, 'player_week', type_='unique')
    op.alter_column('player_week', 'points',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
