"""Create metadata field to track weekly player upload metadata

Revision ID: 9c7ef399630d
Revises: 2a956fc2909d
Create Date: 2025-01-26 21:58:59.863248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c7ef399630d'
down_revision: Union[str, None] = '2a956fc2909d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_week_metadata',
    sa.Column('player_week_metadata_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('chunk_start_value', sa.Integer(), nullable=True),
    sa.Column('chunk_size', sa.Integer(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('player_week_metadata_id'),
    sa.UniqueConstraint('season', 'chunk_start_value', 'chunk_size')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_week_metadata')
    # ### end Alembic commands ###
