"""Clean up commit

Revision ID: ba247fba8667
Revises: 3c33325a4dfb
Create Date: 2025-02-23 17:20:08.640935

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ba247fba8667"
down_revision: Union[str, None] = "3c33325a4dfb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("player_week_espn_deprecated")
    op.drop_table("player_week_copy")
    op.drop_table("leauge_weekly_team_deprecated")
    op.drop_table("player_copy")
    op.drop_constraint(
        "player_week_player_season_id_week_key1", "player_week", type_="unique"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "player_week_player_season_id_week_key1",
        "player_week",
        ["player_season_id", "week"],
    )
    op.create_table(
        "player_copy",
        sa.Column("player_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "first_name", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
        sa.Column(
            "last_name", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
        sa.Column(
            "pfref_id", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
    )
    op.create_table(
        "leauge_weekly_team_deprecated",
        sa.Column("league_team_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("week", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "lineup_position", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
        sa.Column("player_season_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_table(
        "player_week_copy",
        sa.Column("player_week_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("player_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("season", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("week", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "points",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("pass_cmp", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("pass_att", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("pass_yds", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("pass_td", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("pass_int", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("sacks", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("sack_yds", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("rush_att", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("rush_yds", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("rush_td", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("targets", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("receptions", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("rec_yds", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("rec_td", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("fumbles", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("xpm", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("xpa", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("fgm", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("fga", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("tm_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("player_season_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_table(
        "player_week_espn_deprecated",
        sa.Column("week", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("passing_attempts", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "passing_completions", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column("passing_yards", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "passing_touchdowns", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "passing_40yard_tds", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "passing_50yard_tds", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "passing_2pt_conversions", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "passing_interceptions", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column("rushing_attempts", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("rushing_yards", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "rushing_touchdowns", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "rushing_40yard_tds", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "rushing_50yard_tds", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "rushing_2pt_conversions", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "receiving_targets", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "receiving_receptions", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column("receiving_yards", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "receiving_touchdowns", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "receiving_40yard_tds", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "receiving_50yard_tds", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "receiving_2pt_conversions",
            sa.INTEGER(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("fumbles", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("fumbles_lost", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "fumbles_recovered_for_td", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column("passing_sacks", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("kicking_xpm", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("kicking_xpa", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("kicking_fgm_0_39", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("kicking_fga_0_39", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "kicking_fgm_40_49", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "kicking_fga_40_49", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "kicking_fgm_50_59", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "kicking_fga_50_59", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "kicking_fgm_60_plus", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "kicking_fga_60_plus", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "defensive_blocked_kick_return_tds",
            sa.INTEGER(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "defensive_interceptions", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "defensive_fumble_recoveries",
            sa.INTEGER(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "defensive_blocked_kicks", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "defensive_safeties", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column("defensive_sacks", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "kickoff_return_touchdowns",
            sa.INTEGER(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "punt_return_touchdowns", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "interception_return_touchdowns",
            sa.INTEGER(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "fumble_return_touchdowns", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "defensive_forced_fumbles", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "defensive_assisted_tackles",
            sa.INTEGER(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "defensive_solo_tackles", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "defensive_passes_defended",
            sa.INTEGER(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "kickoff_return_yards", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "punt_return_yards", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column("punts_returned", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "defensive_points_allowed", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "defensive_yards_allowed", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "defensive_2pt_return", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column("player_season_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
