"""Drop player_id and season from player_week_espn

Revision ID: d0bde6c51e23
Revises: 42a179c6bbaf
Create Date: 2025-02-22 16:50:17.272914

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d0bde6c51e23"
down_revision: Union[str, None] = "42a179c6bbaf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "player_week_espn_player_id_fkey", "player_week_espn", type_="foreignkey"
    )
    op.drop_column("player_week_espn", "player_id")
    op.drop_column("player_week_espn", "season")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "player_week_espn",
        sa.Column("season", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "player_week_espn",
        sa.Column("player_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "player_week_espn_player_id_fkey",
        "player_week_espn",
        "player",
        ["player_id"],
        ["player_id"],
    )
    # ### end Alembic commands ###
