"""Add lineup config to league season table

Revision ID: e389c86bf36b
Revises: 81c2bd0725f5
Create Date: 2025-02-10 20:33:32.388473

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e389c86bf36b"
down_revision: Union[str, None] = "81c2bd0725f5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "league_season",
        sa.Column(
            "lineup_config", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("league_season", "lineup_config")
    # ### end Alembic commands ###
