"""Create ESPN-specific player weeks table

Revision ID: e44c1e45bc71
Revises: e389c86bf36b
Create Date: 2025-02-16 23:28:33.838235

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e44c1e45bc71"
down_revision: Union[str, None] = "e389c86bf36b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "player_week_espn",
        sa.Column("player_week_espn_id", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=True),
        sa.Column("season", sa.Integer(), nullable=False),
        sa.Column("week", sa.Integer(), nullable=False),
        sa.Column("tm_id", sa.String(), nullable=True),
        sa.Column("passing_attempts", sa.Integer(), nullable=True),
        sa.Column("passing_completions", sa.Integer(), nullable=True),
        sa.Column("passing_yards", sa.Integer(), nullable=True),
        sa.Column("passing_touchdowns", sa.Integer(), nullable=True),
        sa.Column("passing_40yard_tds", sa.Integer(), nullable=True),
        sa.Column("passing_50yard_tds", sa.Integer(), nullable=True),
        sa.Column("passing_2pt_conversions", sa.Integer(), nullable=True),
        sa.Column("passing_interceptions", sa.Integer(), nullable=True),
        sa.Column("rushing_attempts", sa.Integer(), nullable=True),
        sa.Column("rushing_yards", sa.Integer(), nullable=True),
        sa.Column("rushing_touchdowns", sa.Integer(), nullable=True),
        sa.Column("rushing_40yard_tds", sa.Integer(), nullable=True),
        sa.Column("rushing_50yard_tds", sa.Integer(), nullable=True),
        sa.Column("rushing_2pt_conversions", sa.Integer(), nullable=True),
        sa.Column("receiving_targets", sa.Integer(), nullable=True),
        sa.Column("receiving_receptions", sa.Integer(), nullable=True),
        sa.Column("receiving_yards", sa.Integer(), nullable=True),
        sa.Column("receiving_touchdowns", sa.Integer(), nullable=True),
        sa.Column("receiving_40yard_tds", sa.Integer(), nullable=True),
        sa.Column("receiving_50yard_tds", sa.Integer(), nullable=True),
        sa.Column("receiving_2pt_conversions", sa.Integer(), nullable=True),
        sa.Column("fumbles", sa.Integer(), nullable=True),
        sa.Column("fumbles_lost", sa.Integer(), nullable=True),
        sa.Column("fumbles_recovered_for_td", sa.Integer(), nullable=True),
        sa.Column("passing_sacks", sa.Integer(), nullable=True),
        sa.Column("kicking_xpm", sa.Integer(), nullable=True),
        sa.Column("kicking_xpa", sa.Integer(), nullable=True),
        sa.Column("kicking_fgm_0_39", sa.Integer(), nullable=True),
        sa.Column("kicking_fga_0_39", sa.Integer(), nullable=True),
        sa.Column("kicking_fgm_40_49", sa.Integer(), nullable=True),
        sa.Column("kicking_fga_40_49", sa.Integer(), nullable=True),
        sa.Column("kicking_fgm_50_59", sa.Integer(), nullable=True),
        sa.Column("kicking_fga_50_59", sa.Integer(), nullable=True),
        sa.Column("kicking_fgm_60_plus", sa.Integer(), nullable=True),
        sa.Column("kicking_fga_60_plus", sa.Integer(), nullable=True),
        sa.Column("defensive_blocked_kick_return_tds", sa.Integer(), nullable=True),
        sa.Column("defensive_interceptions", sa.Integer(), nullable=True),
        sa.Column("defensive_fumble_recoveries", sa.Integer(), nullable=True),
        sa.Column("defensive_blocked_kicks", sa.Integer(), nullable=True),
        sa.Column("defensive_safeties", sa.Integer(), nullable=True),
        sa.Column("defensive_sacks", sa.Integer(), nullable=True),
        sa.Column("kickoff_return_touchdowns", sa.Integer(), nullable=True),
        sa.Column("punt_return_touchdowns", sa.Integer(), nullable=True),
        sa.Column("interception_return_touchdowns", sa.Integer(), nullable=True),
        sa.Column("fumble_return_touchdowns", sa.Integer(), nullable=True),
        sa.Column("defensive_forced_fumbles", sa.Integer(), nullable=True),
        sa.Column("defensive_assisted_tackles", sa.Integer(), nullable=True),
        sa.Column("defensive_solo_tackles", sa.Integer(), nullable=True),
        sa.Column("defensive_passes_defended", sa.Integer(), nullable=True),
        sa.Column("kickoff_return_yards", sa.Integer(), nullable=True),
        sa.Column("punt_return_yards", sa.Integer(), nullable=True),
        sa.Column("punts_returned", sa.Integer(), nullable=True),
        sa.Column("defensive_points_allowed", sa.Integer(), nullable=True),
        sa.Column("defensive_yards_allowed", sa.Integer(), nullable=True),
        sa.Column("defensive_2pt_return", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["player.player_id"],
        ),
        sa.PrimaryKeyConstraint("player_week_espn_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("player_week_espn")
    # ### end Alembic commands ###
