"""Add pfref_id to team table

Revision ID: ef7cc5d54adb
Revises: 639c1bee4462
Create Date: 2025-01-23 21:19:14.177244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef7cc5d54adb'
down_revision: Union[str, None] = '639c1bee4462'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('team_pfref_id', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'team_pfref_id')
    # ### end Alembic commands ###
