"""Refactor player week relationships in db

Revision ID: f29e320a3a83
Revises: d0bde6c51e23
Create Date: 2025-02-22 22:31:36.204957

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f29e320a3a83"
down_revision: Union[str, None] = "d0bde6c51e23"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("league_weekly_team", sa.Column("player_week_id", sa.Integer()))
    op.create_foreign_key(
        None,
        "league_weekly_team",
        "player_week",
        ["player_week_id"],
        ["player_week_id"],
    )
    op.add_column(
        "player_week", sa.Column("player_season_id", sa.Integer(), nullable=True)
    )
    op.drop_constraint(
        "player_week_player_id_season_week_key", "player_week", type_="unique"
    )
    op.create_unique_constraint(None, "player_week", ["player_season_id", "week"])
    op.create_foreign_key(
        None, "player_week", "player_season", ["player_season_id"], ["player_season_id"]
    )
    # NOTE: For player_week data fields from reference, don't delete, just remove from ORM
    op.add_column(
        "player_week_espn", sa.Column("player_week_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        None, "player_week_espn", "player_week", ["player_week_id"], ["player_week_id"]
    )
    op.drop_column("player_week_espn", "tm_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "player_week_espn",
        sa.Column("tm_id", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "player_week_espn", type_="foreignkey")
    op.drop_column("player_week_espn", "player_week_id")
    op.add_column(
        "player_week",
        sa.Column("rush_yds", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "player_week",
        sa.Column("sack_yds", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "player_week",
        sa.Column("targets", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "player_week",
        sa.Column("pass_cmp", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "player_week",
        sa.Column("pass_att", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "player_week",
        sa.Column("fga", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "player_week",
        sa.Column("pass_int", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "player_week",
        sa.Column("pass_yds", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "player_week",
        sa.Column("rush_att", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "player_week",
        sa.Column("rec_yds", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "player_week",
        sa.Column("fumbles", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "player_week",
        sa.Column("pass_td", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "player_week",
        sa.Column("rec_td", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "player_week",
        sa.Column("rush_td", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "player_week",
        sa.Column("xpm", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "player_week",
        sa.Column("xpa", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "player_week",
        sa.Column(
            "points",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "player_week",
        sa.Column("receptions", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "player_week",
        sa.Column("sacks", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "player_week",
        sa.Column("fgm", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "player_week", type_="foreignkey")
    op.drop_constraint(None, "player_week", type_="unique")
    op.create_unique_constraint(
        "player_week_player_id_season_week_key",
        "player_week",
        ["player_id", "season", "week"],
    )
    op.drop_column("player_week", "player_season_id")
    op.drop_constraint(None, "league_weekly_team", type_="foreignkey")
    op.alter_column(
        "league_weekly_team", "player_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "league_weekly_team", "week", existing_type=sa.INTEGER(), nullable=False
    )
    op.drop_column("league_weekly_team", "player_week_id")
    # ### end Alembic commands ###
