"""Add other platform_ids to players table; make pfref_id unique

Revision ID: fa75498f5d80
Revises: 823540d93a0c
Create Date: 2025-02-03 22:31:31.447427

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fa75498f5d80"
down_revision: Union[str, None] = "823540d93a0c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("player", sa.Column("espn_id", sa.String(length=50), nullable=True))
    op.add_column(
        "player", sa.Column("sleeper_bot_id", sa.String(length=50), nullable=True)
    )
    op.add_column(
        "player", sa.Column("fantasy_pros_id", sa.String(length=50), nullable=True)
    )
    op.add_column("player", sa.Column("yahoo_id", sa.String(length=50), nullable=True))
    op.add_column(
        "player", sa.Column("cbs_player_id", sa.String(length=50), nullable=True)
    )
    op.create_unique_constraint(None, "player", ["pfref_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "player", type_="unique")
    op.drop_column("player", "cbs_player_id")
    op.drop_column("player", "yahoo_id")
    op.drop_column("player", "fantasy_pros_id")
    op.drop_column("player", "sleeper_bot_id")
    op.drop_column("player", "espn_id")
    # ### end Alembic commands ###
